name: "Ccache Setup"
description: "Setup ccache"

inputs:
  CONFIGURATION_PATH_CCACHE:
    description: "ccache configuration path"
    required: true
    default: ".env/ccache"
  LOG_PATH:
    description: "path for various log files"
    required: true
    default: ".log"
  CACHE_PATH:
    description: "path for various caches"
    required: true
    default: ".cache"
  CCACHE_KEY:
    description: "Unique cache key for ccache"
    required: true
    default: "ccache-${{ runner.os }}-${{ github.repository_owner }}-${{ github.event.repository.name }}"

runs:
  using: "composite"
  steps:
    - name: ccache setup configuration
      shell: bash
      run: |
        ccache_path="${{ inputs.CACHE_PATH }}/ccache"
        ccache_log_file="${{ inputs.LOG_PATH }}/ccache"

        mkdir -p $ccache_path

        echo "export CCACHE_MAXSIZE=512M" >> "${{ inputs.CONFIGURATION_PATH_CCACHE }}"
        echo "export CCACHE_COMPRESS=true" >> "${{ inputs.CONFIGURATION_PATH_CCACHE }}"

        # https://stackoverflow.com/questions/53659419/no-hits-in-gitlab-ci-for-ccache
        echo "export CCACHE_COMPILERCHECK=content" >> "${{ inputs.CONFIGURATION_PATH_CCACHE }}"

        echo "export CCACHE_BASEDIR=$GITHUB_WORKSPACE" >> "${{ inputs.CONFIGURATION_PATH_CCACHE }}"
        echo "export CCACHE_DIR=$GITHUB_WORKSPACE/$ccache_path" >> "${{ inputs.CONFIGURATION_PATH_CCACHE }}"

        echo "export CCACHE_LOGFILE=$GITHUB_WORKSPACE/$ccache_log_file" >> "${{ inputs.CONFIGURATION_PATH_CCACHE }}"

    - name: ccache restore
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.CACHE_PATH }}/ccache
        key: ${{ inputs.CCACHE_KEY }}
        restore-keys: |
          ${{ inputs.CCACHE_KEY }}-

    - name: ccache update
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/cache@v4
      with:
        path: ${{ inputs.CACHE_PATH }}/ccache
        key: ${{ inputs.CCACHE_KEY }}-${{ github.run_id }}
        restore-keys: |
          ${{ inputs.CCACHE_KEY }}-
