name: "ESP-IDF Project Setup"
description: "Setup ESP-IDF environment"
inputs:
  IDF_PATH:
    description: "Path where ESP-IDF is installed"
    required: true
    default: "esp-idf"
  IDF_VERSION:
    description: "ESP-IDF version"
    required: true
    default: "v5.3.1"
runs:
  using: "composite"
  steps:
    - name: esp32 install prerequisites
      shell: bash
      run: |
        set -xe
        sudo apt-get update
        sudo apt-get install -y \
            git wget flex bison gperf python3 python3-pip python3-venv \
            cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

    - name: esp32 cache ESP-IDF
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.IDF_PATH }}
          ~/.espressif
        key: esp-idf-${{ runner.os }}-${{ inputs.IDF_VERSION }}

    - name: Setup ESP-IDF
      shell: bash
      run: |
        if [ ! -d "${{ inputs.IDF_PATH }}" ]; then
            set -xe
            git clone --single-branch -b ${{ inputs.IDF_VERSION }} \
                --recursive https://github.com/espressif/esp-idf.git ${{ inputs.IDF_PATH }}
        fi

        cd ${{ inputs.IDF_PATH }}
        ./install.sh
